version: "3.9"

services:
  web:
    build: ./Save_all
    env_file:
      - .env
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
    expose:
      - 8000
    ports:
      - "127.0.0.1:8000:8000"


  nginx:
    image: nginx:latest
    volumes:
      - static_volume:/code/static
      - media_volume:/code/media
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    # depends_on:
    #   - web
    ports:
      - "8080:80"

volumes:
  static_volume:
  media_volume:
