# Generated by Django 4.2.4 on 2023-08-14 22:49

import ckeditor.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Discussions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, help_text='Max  of 200 characters', max_length=200)),
                ('content', ckeditor.fields.RichTextField(blank=True, help_text='Maximum of 5000 characters', max_length=5000, null=True)),
                ('data_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_update', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likes_discussions', models.ManyToManyField(blank=True, related_name='discussions_likes', to=settings.AUTH_USER_MODEL, verbose_name='likes')),
                ('saves_discussions', models.ManyToManyField(blank=True, related_name='blog_discussions_save', to=settings.AUTH_USER_MODEL, verbose_name='Saved user discussions')),
            ],
            options={
                'verbose_name': 'Discussion',
                'verbose_name_plural': 'Discussions',
            },
        ),
    ]
