# Generated by Django 4.2.4 on 2023-08-08 22:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data_create', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_update', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Create post',
                'verbose_name_plural': 'Create posts',
            },
        ),
    ]
