# Generated by Django 4.2.4 on 2023-08-09 11:49

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=ckeditor.fields.RichTextField(blank=True, help_text='Maximum of 5000 characters', max_length=5000, null=True),
        ),
    ]
