# Generated by Django 4.2.4 on 2023-08-13 13:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0011_post_likes_post_post_saves_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='likes_post',
            field=models.ManyToManyField(blank=True, related_name='post_likes', to=settings.AUTH_USER_MODEL, verbose_name='likes'),
        ),
        migrations.AlterField(
            model_name='post',
            name='saves_posts',
            field=models.ManyToManyField(blank=True, related_name='blog_posts_save', to=settings.AUTH_USER_MODEL, verbose_name='Saved user posts'),
        ),
    ]
