# Generated by Django 4.2.4 on 2023-08-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_post_likes_post_alter_post_saves_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(db_index=True, help_text='Maximum of 200 characters', max_length=200, verbose_name='Заголовок'),
        ),
    ]
