# Generated by Django 4.2.4 on 2023-08-20 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='Save_all/other_static/bootstrap5/assets/img/pixlr-bg.png', upload_to='Save_all/media/profiles_img/'),
        ),
    ]
